---
title: "Tests"
output: html_document
date: "`r Sys.Date()`"
---

Surv_Pred must be able to :
 - read the existing survival database with treatment group based on that column with maximum complexity / combination.
 - extract data from existing survival database
 - create projections and use survplot to return them according to the desired factors
 
 
 Info table we need to extract information from surv_database as surv_db_ref,
 We need:
 
 What if first I make a curves extractor function from the surv_database, in which case we would need:
 - the database
 - the pathogen
 - the study.id of interest (%in%) 
 - the factors (column name and contents)

 So in this dataset, every row would represent a curve i guess. 
 
 So the function will be like:
 
 Surv_Select() #Surv select should also remove NA column contents I think. Basically this is equivalent to dplyr::semi_join() so we will use that instead. This will be quite convenient because then we can just semi_join() and select the correct groups. seems to work nicely with NA values (ignored). I mean at most we will have like 3-4 rows as the dataframe to reference as the filtering guide, so its not going to be too work intensive. Ok you know what I think I need to put semi_join inside Surv_Pred(). This is in order to also recognize the factors used and the relevant survival groups (per row of the semi_join guide data).
 
```{r}
# Surv_Pred = function(surv_db,
#                      factors,
#                      ref_surv_db, #maybe enable this to process the survival database. Because i'll need that if I want to do predictions based on multiple reference groups..
#                      ref_surv_select = NULL,
#                      pred_tte = NULL,
#                      pred_dailybin = TRUE, #arguments to be passed to survplots
#                      pred_phi = 1.5, #arguments to be passed to survplots
#                      pred_lambda = NULL, #arguments to be passed to survplots
#                      plot_save = TRUE, #arguments to be passed to survplots?
#                      plot_prefix = "ONDA_XX"){ #arguments to be passed to survplots

 surv_db_ref = surv_db_ex[surv_db_ex$Trt.ID == "A", ]

 #Set 0 offset time
 ref_TTE0 = surv_db_ref$TTE

 #Default pred_tte
 if(is.null(pred_tte)) {stop("You must specifiy the time (tte) of the predicted survival.")}

 #Initialize dataframes
 pred_db = data.frame()

 #Determine experimental design
 if(!is.null(surv_select) & length(unique(surv_db_ref$Trt.ID)) > 1) { #must adjust this to refer to column with maximum combinations of factor levels. Ok so I have to figure out the relevant factors here.
   stop("surv_db_ref must contain only one reference group.")
 }

#This whols section is garbage I think we can remove this main reason being that Surv_Plots() already deal with one tank situations no? I mean it kind of has to in other to plot the dataset no?
 # exp_design = ifelse((length(unique(surv_db$Trt.ID)) == length(unique(surv_db$Tank.ID))) &
 #                       (length(unique(surv_db_ref$Trt.ID)) == length(unique(surv_db_ref$Tank.ID))),
 #                       "single_tank", "multi-tank")
 # 
 # #Set parameters for ref_bshaz estimation. #Rather set the dailybin = TRUE, and pred_phi stuff as default parameters? Or Maybe we can use surv_plots? And then the parameters would be the arguments passed to surv_plots through Surv_Pred.
 # if(exp_design == "single-tank") {
 #   if(pred_dailybin == TRUE) {dbin <- max(surv_db_ref$TTE)} else {dbin <- NULL}
 # } else {
 #   pred_phi = NULL
 #   pred_lambda = NULL
 #   pred_dailybin = FALSE
 #   dbin = NULL
 # }

 # #Get reference level hazard curve
 # ref_id = levels(as.factor(surv_db_ref$Trt.ID))
 # surv_db_ref$Trt.ID = paste("ref", ref_id)

 #This is fine for now, but in the future I must take of the shrimp studies with one animal per tank.
 sink(tempfile())
 if(exp_design == "single-tank"){
   ref_bshaz = bshazard::bshazard(data = surv_db_ref, survival::Surv(TTE, Status) ~ 1,
                                  verbose = FALSE, phi = pred_phi, lambda = pred_lambda,
                                  nbin = dbin)
 } else {
   ref_bshaz = bshazard::bshazard(data = surv_db_ref, survival::Surv(TTE, Status) ~ Tank.ID,
                                  verbose = FALSE, phi = pred_phi, lambda = pred_lambda,
                                  nbin = dbin)
 }
 sink()
 #here we need to change ref_bshaz$hazard and ref_bshazard$times to an interpolated version using approx().

 #Produce offset times. Enable only in one group situations otherwise the plotting becomes too insane? Maybe here we loop by group and have the offset groups refering to difference reference datasets and then we have the actual multiple databaset due to use of the survival database.
 
 # show_offset = TRUE
 # if(show_offset == TRUE) {ref_tte_offset_vec <- c(-1, 0, 1) * 2} else {ref_tte_offset_vec <- 0}

 #Repeat for different offset times
 # for(ref_tte_offset in ref_tte_offset_vec) {

 #Make the multi group here... Maybe you just make a new column called group and we refer to that. Next, depending on the activation of tte_offset or number of groups we can just change the legend title. 
 
   #Ensure positive TTE
   surv_db = surv_db[surv_db$TTE > 0, ]
   surv_db_ref$TTE = ref_TTE0 + ref_tte_offset
   surv_db_ref = surv_db_ref[surv_db_ref$TTE > 0, ]

   #Print warning message if surv_db_ref end TTE < pred_tte
   if(max(surv_db_ref$TTE) < pred_tte) {
     warning(paste(sep = "", "The desired 'pred_tte' (", pred_tte,
                   ") is greater than the maximum available in the reference database (",
                   max(surv_db_ref$TTE) ,") given the TTE offset of ", ref_tte_offset,
                   ". For this offset, predictions are for 'pred_tte' ", ref_tte_offset,
                   " (i.e. TTE = ", max(surv_db_ref$TTE),")."))
   }
   
   #Add another for loop somewhere here or higher to predict based on the different reference groups in surv_db_ref?

   #Loop for every treatment #must refactor to complex groups available
   for(pred_trt in levels(as.factor(surv_db$Trt.ID))) {

     #Combine reference and observed hazard dataframes
     surv_db_f = surv_db[surv_db$Trt.ID == pred_trt,]
     comb_db = rbind(surv_db_ref, surv_db_f)
     comb_db$Trt.ID = relevel(as.factor(comb_db$Trt.ID), ref = paste("ref", ref_id))

     min2_tte = max(min(surv_db_f$TTE), min(surv_db_ref$TTE))
     max_tte = max(surv_db_f$TTE)

     #Predict End SR and HR using different cuts
     for(cut_day in min2_tte:max_tte) { #Do  I really need this? I dont think so.. I can for loop and create prediction over time..
       comb_db2 = survival::survSplit(comb_db, cut = cut_day, end = "TTE", event = "Status", episode = "Obs")
       comb_db2 = comb_db2[comb_db2$Obs == 1, ] #selecting phase 1 data only. We can study discrepancies over time.

       #HR Calculation
       cox_comp = suppressWarnings(coxme::coxme(survival::Surv(TTE, Status) ~ Trt.ID + (1|Tank.ID),
                                                data = comb_db2))
       pred_HR = exp(coef(cox_comp))

       #SR Calculation. Yeah I think we need to ditch this method.
       # ref_bshaz_t = data.frame(hazard = ref_bshaz$hazard[ref_bshaz$time < pred_tte],
       #                          time = ref_bshaz$time[ref_bshaz$time < pred_tte])
       # 
       # #Uses the shape of the reference hazard curve throughout. Yeah I think we need to ditch this method in favor of adaptive.
       # if(pred_method == "simple") {
       #   cumhaz = DescTools::AUC(x = c(ref_bshaz_t$time),
       #                           y = c(ref_bshaz_t$hazard) * pred_HR)
       #   pred_SR = 100 * exp(-cumhaz)
       # }

       #Uses obseved survival and the reference hazard curve. Basically using existing survival curve + future un-observed and hypothesized hazard curve
       if(pred_method == "adaptive") {

         #Split survival data for calculating cumulative hazard using the reference and the observable hazard curve. Ok this is just a bad idea it seems. Why not just calculate the last(survprob) from the surv_db using survival()? The grouping structure will be based on the most complex column and then we can remove all the shit on the left hand side of the equal sign because thats the string added by survival()
         # cut_db = survival::survSplit(surv_db, cut = cut_day + 1, end = "TTE", event = "Status", episode = "Obs")
         # precut_db = cut_db[cut_db$Obs == 1, ]
         # 
         # #Precut surv using surv_db
         # precut_surv = min(summary(survival::survfit(survival::Surv(TTE, Status) ~ 1,
         #                                   data = droplevels(precut_db[precut_db$Trt.ID == pred_trt,])))$surv)
         # cumhaz_precut = -log(precut_surv)

         #Postcut bshaz using surv_db_ref
         #Ok so this section below is what I really need to loop. Then we can expand the Pred_Stats dataframe which can contain the offset value instead if having another dataframe called Pred_Stats_Offset?
         postcut_bshaz = ref_bshaz_t[ref_bshaz_t$time >= cut_day,] #to be honest here it should be inclusive on the cut day 
         if(nrow(postcut_bshaz) > 0) {
           cumhaz_postcut = DescTools::AUC(x = c(postcut_bshaz$time),
                                           y = c(postcut_bshaz$hazard) * pred_HR) #should work nicely as long as the interpolation is ok
         } else {
           cumhaz_postcut = 0
         }

         #ah fk. Is this why I need the cumhaz precut? Can't i just calculate cumhaz_precut though from the log(end_sr)?
         #so here I can go cumhaz_precut = -log(end_sr)
         pred_SR = 100 * exp(-(cumhaz_precut + cumhaz_postcut))
       }

       #Rbind to create prediction database
       if(ref_tte_offset == 0) {
         Pred_Stats = rbind(Pred_Stats, data.frame(Trt.ID = pred_trt,
                                                   TTE_Used = cut_day,
                                                   pred_SR,
                                                   pred_HR))
       } else {
         Pred_Stats_Offset = rbind(Pred_Stats_Offset, data.frame(ref_tte_offset,
                                                                 Trt.ID = pred_trt,
                                                                 TTE_Used = cut_day,
                                                                 pred_SR,
                                                                 pred_HR))
       }
     }
   }
 # }
   
 #Whats this for? Delete?
 row.names(Pred_Stats) = NULL
 row.names(Pred_Stats_Offset) = NULL

 #Create plots representing survival and hazard predictions over time
 #xbreaks = round((max(Pred_Stats$TTE_Used) - min(Pred_Stats$TTE_Used)) / 5) #I think we can delete this?
 
 #
 # I think we can delete all this prediction history stuff. Because now this is not our measure of reliability.
 # Pred_SR_Plot = ggplot(data = Pred_Stats, aes(x = TTE_Used, y = pred_SR, color = Trt.ID)) +
 #   geom_point() +
 #   geom_line() +
 #   facet_wrap(~Trt.ID) +
 #   scale_y_continuous(name = paste("Predicted SR at a TTE of", pred_tte),
 #                      breaks = seq(0, 100, 20), limits = c(0, 100)) +
 #   scale_x_continuous(name = "TTEs used to predict", breaks = seq(0, 100, xbreaks)) +
 #   ggtitle("SR Prediction History")
 # 
 # Pred_HR_Plot = ggplot(data = Pred_Stats, aes(x = TTE_Used, y = pred_HR, color = Trt.ID)) +
 #   geom_point() +
 #   geom_line() +
 #   facet_wrap(~Trt.ID) +
 #   scale_y_continuous(name = paste("Predicted HR at a TTE of", pred_tte), n.breaks = 6) +
 #   scale_x_continuous(name = "TTEs used to predict", breaks = seq(0, 100, xbreaks)) +
 #   ggtitle("HR Prediction History")
 # 
 # if(show_offset == TRUE){
 #   Pred_SR_Plot = Pred_SR_Plot +
 #     geom_line(data = Pred_Stats_Offset[Pred_Stats_Offset$ref_tte_offset == ref_tte_offset_vec[1],],
 #               linetype = "dashed", show.legend = FALSE) +
 #     geom_line(data = Pred_Stats_Offset[Pred_Stats_Offset$ref_tte_offset == ref_tte_offset_vec[3],],
 #               linetype = "dashed", show.legend = FALSE)
 # 
 #   Pred_HR_Plot = Pred_HR_Plot +
 #     geom_line(data = Pred_Stats_Offset[Pred_Stats_Offset$ref_tte_offset == ref_tte_offset_vec[1],],
 #               linetype = "dashed", show.legend = FALSE) +
 #     geom_line(data = Pred_Stats_Offset[Pred_Stats_Offset$ref_tte_offset == ref_tte_offset_vec[3],],
 #               linetype = "dashed", show.legend = FALSE)
 # }

 #Create Projection Plots -- this is what we want
 surv_db_ref$TTE = ref_TTE0
 #What on earth is ref_plot_db for? ah it seems that it is what is geom stepped but we dont have to resestimate these...
 # ref_plot_db = layer_data(Surv_Plots(surv_db = surv_db_ref,
 #                                     plot = "surv",
 #                                     plot_save = FALSE))
 # ref_plot_db2 = layer_data(Surv_Plots(surv_db = surv_db_ref,
 #                                      plot = "haz",
 #                                      lambda = pred_lambda,
 #                                      phi = pred_phi,
 #                                      dailybin = pred_dailybin,
 #                                      plot_save = FALSE))

 Comp_SR_Plot = Surv_Plots(surv_db = surv_db,
                           plot = "surv",
                           xlim = c(0, pred_tte),
                           plot_save = FALSE) +
     geom_step(data = ref_plot_db, inherit.aes = FALSE, show.legend = FALSE,
             aes(x = x, y = y), linewidth = 1) +
   ggtitle("Survival Rate Comparisons")

 Comp_HR_Plot = Surv_Plots(surv_db = surv_db,
                           plot = "haz",
                           xlim = c(0, pred_tte),
                           lambda = pred_lambda,
                           phi = pred_phi,
                           dailybin = pred_dailybin,
                           plot_save = FALSE) +
   geom_line(data = ref_plot_db2, inherit.aes = FALSE, show.legend = FALSE, aes(x = x, y = y),
             linewidth = 1) +
   ggtitle("Hazard Rate Comparisons")

 #Save plots
 if(plot_save == TRUE) {
   ggsave(plot = Pred_SR_Plot, filename = paste(sep = "", plot_prefix, " SR Prediction History.tiff"),
          dpi = 400, width = 7, height = 4.1)
   ggsave(plot = Pred_HR_Plot, filename = paste(sep = "", plot_prefix, " HR Prediction History.tiff"),
          dpi = 400, width = 7, height = 4.1)
   ggsave(plot = Comp_SR_Plot, dpi = 400, width = 6, height = 4,
          filename = paste(sep = "", plot_prefix, " Survival Comparisons.tiff"))
   ggsave(plot = Comp_HR_Plot, dpi = 400, width = 6, height = 4,
          filename = paste(sep = "", plot_prefix, " Hazard Comparisons.tiff"))
 }

 #Return Outputs
 Output_list = list(Comp_SR_Plot = Comp_SR_Plot,
                    Comp_HR_Plot = Comp_HR_Plot)
                    #Pred_SR_Plot = Pred_SR_Plot,
                    #Pred_HR_Plot = Pred_HR_Plot)

 return(Output_list)
}
```

