---
title: "MultiVar() on QCATC1092_DB"
output: html_document
date: "`r Sys.Date()`"
---

1. Installing and loading the package (you only have to install once)
```{r Setup package}
remotes::install_github("sean4andrew/safuncs")
library(safuncs)
```

2. Load dataset
```{r Setup data}
QCATC1092_DB = read.csv(file = "ONDA1092-4 Gene R Ready Format.csv")[-97,] # remove data point #X - clear, strong outlier
QCATC1092_DB$Month = factor(QCATC1092_DB$Month, levels = c("May", "Jun", "Jul", "Oct", "Nov", "Dec")) # reorder factor levels

#NOTE: "Oct" data represents the resampled October data. It was assumed the original Oct dataset was wrong, hence the resampling.
head(QCATC1092_DB)
```

3. Running MultiVar()
```{r Run MultiVar()}
MultiVar(multivar_db = QCATC1092_DB,
         values_cols = 4:6,
         factors_cols = 2,
         factors_facet = c("col1", "col2"),
         missing_method = "na_omit",
         boxplot_filled = TRUE,
         boxplot_var_sep = TRUE,
         boxplot_x_wrap = 4,
         boxplot_points = TRUE,
         plot_out_R = TRUE)
```


```{r Run MultiVar()}
boxplot_db = layer_data(output_ex)
layer_data(output_ex)

boxplot_db2 = layer_data(output_ex2)
layer_data(output_ex2)

boxplot_db3 = layer_data(output_ex3)
layer_data(output_ex3)
```


```{r Run MultiVar()}
output_ex + geom_text(data = boxplot_db, aes(x = as.numeric(x), y = upper, label = group, fill = NULL), 
                      nudge_y = diff(layer_scales(output_ex)$y$range$range) * 0.04,
                      nudge_x = diff(range(boxplot_db$x)) * 0.018,
                      show.legend = FALSE)
```
```{r}
#boxplot_db2$second_factor = rep(levels(factor(output_ex2$data$second_factor)), each = length(unique(boxplot_db2$group)))
boxplot_db2$second_factor = cld_obj$second_factor
boxplot_db2$base_factor = cld_obj$base_factor
boxplot_db2$group = cld_obj$.group
# the dynamic version is to use levels unique
facet_col = 3
facet_row = 2

output_ex2 + geom_text(data = boxplot_db2, aes(x = base_factor, y = upper, label = group, fill = NULL), 
                      nudge_y = diff(layer_scales(output_ex2)$y$range$range) * 0.04 * facet_row,
                      nudge_x = diff(range(boxplot_db2$x)) * 0.018 * facet_col * 1.5,
                      show.legend = FALSE)


output_ex2 + geom_text(data = boxplot_db2, aes(x = base_factor, y = ymax, label = group, fill = NULL), 
                      nudge_y = diff(layer_scales(output_ex2)$y$range$range) * 0.04 * facet_row,
                      nudge_x = 0,
                      show.legend = FALSE)

output_db = output_ex2$data
lm_obj = lm(data = output_db, values ~ base_factor * second_factor)
cld_obj = data.frame(cld(emmeans(lm_obj, ~ base_factor | second_factor), Letter = letters, sort = FALSE))
```

```{r}
boxplot_list
```

```{r MultiVar() function}
multivar_db = QCATC1092_DB
values_cols = 4:6
factors_cols = 1:2
factors_pool = c("col1", "col2")
factors_facet = c("col1", "col2")
pca_ellipse = c("confidence")
pca_facet_scales = "fixed"
pca_labels = NULL
pca_shapes = FALSE
missing_method = "na_omit"
scale = TRUE
center = TRUE
boxplot_filled = TRUE
boxplot_x_angle = NULL
boxplot_x_wrap = 4
boxplot_x_lab = FALSE
boxplot_x_text = TRUE
boxplot_legend_pos = "right"
boxplot_points = TRUE
boxplot_outliers = FALSE
boxplot_letters = TRUE
boxplot_var_sep = TRUE
colours = NULL
colours_theme = NULL
plot_out_png = FALSE
plot_out_pptx = FALSE
plot_out_R = TRUE

  # Initialize and define objects
  results_doc = officer::read_docx() %>%
    officer::body_add_par(value = "Analyzing the Outcome Variables as a Multivariate Response", style = "heading 1") %>%
    officer::body_add_par("PCA Plots", style = "heading 2") %>%
    officer::body_add_par("") %>%
    officer::body_add_par("")
  results_doc_boxplot = officer::read_docx() %>%
    officer::body_add_par(value = "Analyzing the Outcome Variables Separately", style = "heading 1") %>%
    officer::body_add_par("All Variables in One Plot", style = "heading 2") %>%
    officer::body_add_par("") %>%
    officer::body_add_par("")
  tempf = tempfile(fileext = ".docx")
  pca_list = list(list())
  boxplot_list = list(list())
  dataframe_list = list()
  boxplot_name_vec = c()
  box_height2_vec = c()
  univariate_tests = TRUE # defined in case it is to be converted to an optional output
  knife <- function(x) { # for formatting p-values (mostly)
    if(x < 1e-4) {
      return(format(x, scientific = TRUE, digits = 4))
    } else {
      return(round(x, 4))
    }}
  point_alpha = 0.72
  dodge_width = 0.75
  boxplot_width = 0.65
  jit_width = 0.15
  base_text_size = 2.1
  nudge_y_ratio = 0.1
  layer_count = ifelse(boxplot_points == TRUE, 4, 3)
  point_shape = 21
  box_ratio = 1
  boxplot_letters = ifelse(boxplot_letters == TRUE, 1, 0)
  tc = 0

  # Set path and file names
  if(plot_out_png == TRUE) {
    img_path = file.path(getwd(), paste("MultiVar PNG Figures", format(Sys.Date(), "%d%b%Y")))
    suppressWarnings(dir.create(img_path))
  } else {
    img_path = file.path(tempdir(), "Temp MultiVar PNG Figures")
    suppressWarnings(dir.create(img_path))
  }

  if(plot_out_pptx == TRUE) {
    pptx_name = paste(sep = "", "MultiVar Editable Figures ",
                      format(Sys.Date(), "%d%b%Y"), ".pptx")
    if(file.exists(pptx_name)) {
      file.remove(pptx_name)
    }
  }

  # Get matrix of values
  matrix_values_ori = multivar_db[, values_cols]
  matrix_values = multivar_db[, values_cols]

  # Validation check(s)
  if(length(values_cols) < 2){stop("At least two columns are needed with variable values for proper multivariate analysis. Please add more columns to the 'values_cols' argument.")}
  if(length(factors_cols) > 2){stop("A maximum of two factors are allowed. Please reduce the number of columns specified in 'factors_cols' to ≤ 2.")}
  if(length(factors_cols) != 2) {factors_pool <- "none"}
  if(length(factors_cols) != 2) {factors_facet <- "none"}

  # Address NAs in matrix values
  if(missing_method == "imputation") {
    if(sum(is.na(matrix_values)) > 0) {
      matrix_values = data.frame(missMDA::imputePCA(matrix_values,
                                                    ncp = missMDA::estim_ncpPCA(matrix_values)$ncp)$completeObs)
    }
  }
  if(missing_method == "na_omit") {
    multivar_db_ori = multivar_db
    multivar_db = multivar_db[stats::complete.cases(matrix_values),]
    matrix_values = multivar_db[, values_cols]
  }

  # Get PC values
  pc_values = stats::prcomp(matrix_values, scale = scale, center = center)
  matrix_values$PC1 = PC1 <- pc_values$x[, 1]
  matrix_values$PC2 = PC2 <- pc_values$x[, 2]

  # Get loadings
  load_db = data.frame(load1 = load1 <- pc_values$rotation[, 1] * pc_values$sdev[1],
                       load2 = load2 <- pc_values$rotation[, 2] * pc_values$sdev[2],
                       vars = stringr::str_wrap(width = 15, gsub("\\.", " ", rownames(pc_values$rotation))))

  # Create base database for plotting
  plot_db = cbind(multivar_db[, factors_cols, drop = FALSE], matrix_values)

  # Create base PCA plot
  pca_plot_base = ggplot() +
    geom_point() +
    geom_hline(yintercept = 0, linetype = "dashed") +
    geom_vline(xintercept = 0, linetype = "dashed") +
    theme_minimal() +
    xlab(paste("Principal Component 1 (", round(summary(pc_values)$importance[2, 1] * 100, 1), "%)", sep = "")) +
    ylab(paste("Principal Component 2 (", round(summary(pc_values)$importance[2, 2] * 100, 1), "%)", sep = "")) +
    safuncs::theme_Publication() +
    theme(legend.position = boxplot_legend_pos,
          legend.margin = margin(0, 0, 0, 0),
          legend.spacing.x = unit(0, "mm"),
          legend.spacing.y = unit(0, "mm"),
          plot.margin = unit(c(0.1, 0.1, 0.1, 0.1), "in"),
          strip.text = element_text(size = 10, margin = margin(0.155, 0.1, 0.155, 0.1, unit = "cm")),
          strip.background = element_rect(fill = "grey", color = NA),
          panel.grid.minor = element_line(linewidth = 0.5, color = "grey92"),
          panel.grid.major = element_line(linewidth = 0.5, color = "grey92"))
  if(!is.null(colours_theme)){pca_plot_base <- pca_plot_base + scale_colour_brewer(palette = colours_theme, aesthetics = c("colour", "fill"))}

  # Create base boxplot
  boxplot = ggplot() +
    stat_boxplot(linewidth = 0.83, geom = "errorbar", width = 0.35, position = position_dodge(width = dodge_width), na.rm = TRUE) +
    geom_boxplot(size = 0.73, outlier.size = ifelse(boxplot_outliers == TRUE, 1.1, -1), outlier.fill = NULL, outlier.colour = NULL,
                 outlier.shape = 21, na.rm = TRUE, position = position_dodge(width = dodge_width), width = boxplot_width,
                 outlier.stroke = 0.7) +
    scale_x_discrete(expand = expansion(mult = 0.04, add = 0.38)) +
    geom_text() + 
    safuncs::theme_Publication() +
    theme(legend.position = boxplot_legend_pos,
          legend.margin = margin(0, 0, 0, 0),
          legend.spacing.x = unit(0, "mm"),
          legend.spacing.y = unit(0, "mm"),
          plot.margin = unit(c(0.07, 0.07, 0.07, 0.07), "in"))
  
  if(!is.null(colours_theme)){boxplot <- boxplot + scale_colour_brewer(palette = colours_theme, aesthetics = c("colour", "fill"))}
  if(!is.null(boxplot_x_angle)) {boxplot <- boxplot + theme(axis.text.x = element_text(angle = boxplot_x_angle, hjust = 1))}
  if(!is.null(boxplot_x_wrap)) {boxplot <- boxplot + scale_x_discrete(labels = scales::wrap_format(boxplot_x_wrap),  expand = expansion(mult = 0.04, add = 0.38))}
  if(boxplot_x_text == FALSE) {boxplot <- boxplot + theme(axis.text.x = element_blank())}
  boxplot = boxplot +


  # Colour plots if applicable
  if(!is.null(colours)){
    pca_plot_base = pca_plot_base +
      scale_color_manual(values = colours) +
      scale_fill_manual(values = colours)

    boxplot = boxplot +
      scale_color_manual(values = colours) +
      scale_fill_manual(values = colours)
  }

  # Set default plot dimensions
  pca_width = 6.3
  pca_height = 4.45
  varplot_width = 6.4
  varplot_height = 4.5
  box_width = 6.4 * box_ratio

  # Create factor conditions
  full_conds = c("none", "pooled1", "pooled2", "facet1", "facet2")
  treatment_conds = as.vector(factor(unique(c("none", gsub("col", "pooled", factors_pool),
                                              gsub("col", "facet", factors_facet))), levels = full_conds))

  # Create multiple plots (potentially) to deal with multi factor scenarios
  for(treatment_conds_i in treatment_conds) {

    # Create different databases for plotting in different factor scenarios
    if(treatment_conds_i == "none") {
      plot_db$base_factor = interaction(multivar_db[, factors_cols], sep = " ")
      base_factor_name = ifelse(length(factors_cols) == 1,
                                colnames(multivar_db)[factors_cols], "Combination")
    }
    if(treatment_conds_i %in% c("facet2", "pooled2")) {
      plot_db$base_factor = multivar_db[, factors_cols[1]]
      plot_db$second_factor = multivar_db[, factors_cols[2]]
      base_factor_name = gsub("\\.", " ", colnames(multivar_db)[factors_cols[1]])
      second_factor_name = gsub("\\.", " ", colnames(multivar_db)[factors_cols[2]])
    }
    if(treatment_conds_i %in% c("facet1", "pooled1")) {
      plot_db$base_factor = multivar_db[, factors_cols[2]]
      plot_db$second_factor = multivar_db[, factors_cols[1]]
      base_factor_name = gsub("\\.", " ", colnames(multivar_db)[factors_cols[2]])
      second_factor_name = gsub("\\.", " ", colnames(multivar_db)[factors_cols[1]])
    }

   # Run Univariate Tests
    if(treatment_conds_i == first(treatment_conds)){
      p_no_adj = c()
      contrast_db0 = data.frame()
      contrast_db = data.frame()
      contrast_db2 = data.frame()
      cld_db0 = data.frame()
      cld_db = data.frame()
      cld_db2 = data.frame()
  
      # Get p-values for each variable
      varnames_vec = levels(factor(colnames(multivar_db[, values_cols, drop = FALSE])))
      factors_vec = paste(collapse = " * ", colnames(multivar_db[, factors_cols, drop = FALSE]))
      options(contrasts = c("contr.sum", "contr.poly"))
      for(values_vec_i in varnames_vec) {
        # ANOVA and model fitting
        lm_mod = lm(data = multivar_db, formula = as.formula(paste(values_vec_i, "~", factors_vec)))
        Anova_res = car::Anova(lm_mod, type = 3, test.statistic = "F")
        p_no_adj = c(p_no_adj, as.numeric(na.omit(Anova_res$`Pr(>F)`[-1])))
  
        # Pairwise comparisons
        factor_conds = colnames(multivar_db[, factors_cols, drop = FALSE])
        for(factor_conds_i in factor_conds){
          ## One Factor situations
          if(length(factors_cols) == 1){
            emmeans_obj0 = emmeans::emmeans(lm_mod, as.formula(paste("pairwise ~", factor_conds_i)), adjust = "BH")
            emmeans_obj = emmeans_obj0
            cld_obj0 = data.frame(multcomp::cld(emmeans_obj0, Letter = letters, adjust = "BH"))
            cld_obj0 = cld_obj0[order(cld_obj0[, 1]), ]
            cld_obj = cld_obj0
          }
          ## Two Factor situations
          if(length(factors_cols) == 2) {
            emmeans_obj0 = suppressWarnings(emmeans::emmeans(lm_mod, as.formula(paste("pairwise ~", first(factor_conds), "*",
                                                                               last(factor_conds))),
                                                            adjust = "BH"))
            emmeans_obj = suppressMessages(emmeans::emmeans(lm_mod, as.formula(paste("pairwise ~", factor_conds_i)),
                                                            adjust = "BH"))
            emmeans_obj2 = suppressMessages(emmeans::emmeans(lm_mod,
                                                             as.formula(paste("pairwise ~", factor_conds_i, "|",
                                                                              factor_conds[factor_conds != factor_conds_i])),
                                                             adjust = "BH"))
            cld_obj0 = data.frame(multcomp::cld(emmeans_obj0, Letter = letters, adjust = "BH"))
            cld_obj = data.frame(multcomp::cld(emmeans_obj, Letter = letters, adjust = "BH"))
            cld_obj2 = data.frame(multcomp::cld(emmeans_obj2, Letter = letters, adjust = "BH"))

            cld_obj0 = cld_obj0[order(cld_obj0[, 2], cld_obj0[, 1]), ]
            cld_obj = cld_obj[order(cld_obj[, 1]), ]
            cld_obj2 = cld_obj2[order(cld_obj2[, 2], cld_obj2[, 1]), ]
            
            cld_db2 = rbind(cld_db2, data.frame(Factor = factor_conds_i,
                                                Variable = values_vec_i,
                                                Condition = cld_obj2[, 2],
                                                Compared_Levels = cld_obj2[, 1],
                                                Statistical_Classes = cld_obj2[, 8]))
  
            contrast_db2 = rbind(contrast_db2, data.frame(Factor = factor_conds_i,
                                                          Variable = values_vec_i,
                                                          Condition = data.frame(emmeans_obj2$contrasts)[, 2],
                                                          Contrast = data.frame(emmeans_obj2$contrasts)[, 1],
                                                          Difference = data.frame(emmeans_obj2$contrasts)[, 3],
                                                          P_value = sapply(data.frame(emmeans_obj2$contrasts)[, 7], knife)))
          }
          # Create cld db
          cld_db = rbind(cld_db, data.frame(Factor = factor_conds_i,
                                            Variable = values_vec_i,
                                            Levels = cld_obj[, 1],
                                            Statistical_Classes = cld_obj[, 7]))
  
          # Create contrast db
          contrast_db = rbind(contrast_db, data.frame(Factor = factor_conds_i,
                                                      Variable = values_vec_i,
                                                      Contrast = data.frame(emmeans_obj$contrasts)[, 1],
                                                      Difference = data.frame(emmeans_obj$contrasts)[, 2],
                                                      P_value = sapply(data.frame(emmeans_obj$contrasts)[, 6], knife)))
        }
        cld_db0 = rbind(cld_db0, data.frame(Variable = values_vec_i,
                                            Levels = interaction(sep = " ", cld_obj0[, 1:length(factors_cols)]),
                                            Statistical_Classes = cld_obj0[, ncol(cld_obj0)]))
        contrast_db0 = rbind(contrast_db0, data.frame(Variable = values_vec_i,
                                                      Contrast = data.frame(emmeans_obj0$contrasts)[, 1],
                                                      Difference = data.frame(emmeans_obj0$contrasts)[, 2],
                                                      P_value = sapply(data.frame(emmeans_obj0$contrasts)[, 6], knife)))
      }
    }
    options(contrasts = c("contr.treatment", "contr.poly"))
    
    # Create facet dimensions depending on treatment_conds_i
    facet_num = ifelse(treatment_conds_i %in% c("none", "pooled2", "pooled1"),
                       length(values_cols),
                       length(unique(plot_db$second_factor)))
    facet_col = ifelse(facet_num %in% 1:4, 2, 3)
    facet_row = ceiling(facet_num / facet_col)

    # Modify PCA Plot based on treatment_conds_i
    pca_plot = pca_plot_base
    pca_plot$data = plot_db
    pca_plot$mapping = aes(x = PC1, y = PC2, colour = base_factor, fill = base_factor)
    pca_plot$guides = guides(colour = guide_legend(base_factor_name), fill = guide_legend(base_factor_name),
                             shape = guide_legend(base_factor_name))
    if(pca_shapes == TRUE) {
      if(length(unique(plot_db$base_factor)) <= 6) {pca_plot$layers[[1]] <- geom_point(aes(shape = base_factor), size = 2)}
      if(length(unique(plot_db$base_factor)) > 6) {pca_plot$layers[[1]] <- geom_point(size = 2)}
    } else {pca_plot$layers[[1]] <- geom_point(size = 2)}

    # Add PCA labels
    if("ind" %in% pca_labels) {
      pca_plot = pca_plot + ggrepel::geom_text_repel(show.legend = FALSE, max.overlaps = 20, aes(label = rownames(plot_db)))
    }
    if("var" %in% pca_labels) {
      # Calculate arrow length multiplier as in factoextra::fviz_pca_biplot()
      r0.7 = min((max(PC1) - min(PC1)/(max(load1) - min(load1))), (max(PC2) - min(PC2)/(max(load2) - min(load2)))) * 0.7
      pca_plot$layers = append(pca_plot$layers, geom_segment(data = load_db,
                                                             aes(fill = NULL, color = NULL, x = 0, y = 0,
                                                                 xend = load1 * r0.7, yend = load2 * r0.7),
                                                             color = "black", alpha = 0.8,
                                                             arrow = arrow(length = unit(0.2, "cm"), type = "open"),
                                                             show.legend = FALSE), after = 0)
      text_size_algo = ifelse(treatment_conds_i %in% c("none", "pooled2", "pooled1"),
                              3, 3.4 - (0.6 * facet_col))
      pca_plot = pca_plot + ggrepel::geom_text_repel(show.legend = FALSE, max.overlaps = 20,
                                                     data = load_db, aes(fill = NULL, color = NULL,
                                                                         x = load1 * r0.7, y = load2 * r0.7,
                                                                         label = vars),
                                                     color = "black", size = text_size_algo)
    }

    # Add PCA facets
    if(treatment_conds_i %in% c("facet2", "facet1")) {
      pca_plot = pca_plot + facet_wrap(~ second_factor, ncol = facet_col, nrow = facet_row, scales = pca_facet_scales)

      # Set plot height based on facet
      pca_height = 1.8 + 1.2 * facet_row
    }

    # Add ellipses and store PCA plots in a list
    if("none" %in% pca_ellipse) {pca_list[["none"]][[treatment_conds_i]] <- pca_plot}
    if("confidence" %in% pca_ellipse) {pca_list[["confidence"]][[treatment_conds_i]] <- pca_plot + ggpubr::stat_conf_ellipse(geom = "polygon", alpha = 0.15)}
    if("distribution" %in% pca_ellipse) {pca_list[["distribution"]][[treatment_conds_i]] <- pca_plot + ggplot2::stat_ellipse(type = "norm", geom = "polygon", alpha = 0.15)}
    if("convexhull" %in% pca_ellipse) {pca_list[["convexhull"]][[treatment_conds_i]] <- pca_plot + ggpubr::stat_chull(geom = "polygon", alpha = 0.15)}

    # Save PCA plots
    for(ellipse_i in pca_ellipse) {
      pca_name = paste("PCA", ifelse(treatment_conds_i == "none", "",
                                     paste(" Facet-", second_factor_name, sep = "")),
                       " Ellipse-", tools::toTitleCase(ellipse_i), sep = "")
      if(treatment_conds_i %in% c("pooled2", "pooled1")) {
        pca_name = paste("PCA Pooled-", second_factor_name, " Ellipse-", tools::toTitleCase(ellipse_i), sep = "")
      }

      if(plot_out_pptx){
        eoffice::topptx(figure = pca_list[[ellipse_i]][[treatment_conds_i]],
                        filename = pptx_name,
                        width = pca_width, height = pca_height, append = TRUE)
      }
      ggsave(plot = pca_list[[ellipse_i]][[treatment_conds_i]], filename = paste(sep = "", pca_name, ".png"),
             path = img_path, dpi = 600, width = pca_width, height = pca_height)
      results_doc = officer::body_add_img(x = results_doc, sr = file.path(img_path, paste(pca_name, ".png", sep = "")),
                                          width = pca_width, height = pca_height) %>%
        officer::body_add_par(value = pca_name, style = "graphic title") %>%
        officer::body_add_par("")
      if((last(treatment_conds) == treatment_conds_i) & (last(pca_ellipse) == ellipse_i)){} else {
        results_doc <- results_doc %>% officer::body_add_par("")
      }
    }

    # Create variables plot, contributions table & variable correlations plot
    if(last(treatment_conds) == treatment_conds_i) {
      # Note for PCA
      results_doc = results_doc %>%
        officer::body_add_par(paste(sep = "", "The ", round(summary(pc_values)$importance[2, 1] * 100, 1), "% and ",
                                    round(summary(pc_values)$importance[2, 2] * 100, 1), "% values in the axes of the figures above describe the percent variation in the data explained by the first and second principal components, respectively."), style = "Normal") %>%
        officer::body_add_par("") %>%
        officer::body_add_par("")

      # Create variable plots
      varplot_name = "Correlation of Variables to PCs"
      varplot = factoextra::fviz_pca_var(pc_values, repel = TRUE) +
        xlab(expression(paste(sep = "", "Correlation (", italic(r), ") to PC1"))) +
        ylab(expression(paste(sep = "", "Correlation (", italic(r), ") to PC2"))) +
        safuncs::theme_Publication() +
        theme(plot.title = element_blank(),
              axis.line = element_line(color = "black", linewidth = 0.4),
              plot.margin = unit(c(0, 0.18, 0, 0.18), "in"),
              panel.grid.major = element_line(linewidth = 0.5, color = "grey92"),
              panel.grid.minor = element_line(linewidth = 0.5, color = "grey92"))
      varplot_layer3 = varplot$layers[[3]]
      varplot$layers[[3]] = ggrepel::geom_text_repel(data = varplot$data,
                                                     aes(x = x, y = y,
                                                         label = stringr::str_wrap(gsub("\\.", " ", name), width = 15)),
                                                     nudge_x = 0, nudge_y = 0, size = 3.75, color = "darkblue",
                                                     box.padding = 0, min.segment.length = 0.3, segment.colour = "darkblue")
      varplot$layers[[1]] = varplot_layer3

      # Save plot
      if(plot_out_pptx == TRUE) {
        eoffice::topptx(figure = varplot, filename = pptx_name,
                        width = varplot_width, height = varplot_height, append = TRUE)
      }
      ggsave(plot = varplot, filename = paste(sep = "", varplot_name, ".png"), path = img_path,
             dpi = 600, width = varplot_width, height = varplot_height)

      # Create correlations table
      correl_db = data.frame(cor(matrix_values)) %>% tibble::rownames_to_column(" ")
      colnames(correl_db) = gsub("\\.", " ", colnames(correl_db))
      correl_db[, 1] = gsub("\\.", " ", correl_db[, 1])

      tc = tc + 1
      correl_tab = flextable::flextable(correl_db) %>%
        flextable::set_caption(caption = paste(sep = "", "Table ", tc, ". Pearson correlation coefficient (r) between variables and principal components")) %>%
        flextable::colformat_double(digits = ifelse(length(values_cols) < 5, 4, 3)) %>%
        flextable::line_spacing(space = ifelse(length(values_cols) < 5, 1, 0.8), part = "all") %>%
        flextable::fontsize(size = ifelse(length(values_cols) < 5, 11, 9), part = "all") %>%
        flextable::set_table_properties(layout = "autofit", width = 1)

      # Create contribution table
      contrib_db = data.frame(Variable = gsub("\\.", " ", names(pc_values$rotation[,1])),
                              Contrib.PC1 = as.vector(100 * pc_values$rotation[,1]^2),
                              Eigenvec.PC1 = as.vector(pc_values$rotation[,1]),
                              Contrib.PC2 = as.vector(100 * pc_values$rotation[,2]^2),
                              Eigenvec.PC2 = as.vector(pc_values$rotation[,2])) %>% dplyr::arrange(desc(Contrib.PC1))

      tc = tc + 1
      contrib_tab = flextable::flextable(contrib_db) %>%
        flextable::set_caption(caption = paste(sep = "", "Table ", tc,
                                               ". Contribution of variables to principal components")) %>%
        flextable::set_table_properties(layout = "autofit", width = 1) %>%
        flextable::bold(bold = TRUE, part = "header")

      # Save the three results (1 plots, 2 table) in the word document
      results_doc = results_doc %>%
        officer::body_add_img(sr = file.path(img_path, paste(varplot_name, ".png", sep = "")),
                              width = varplot_width, height = varplot_height) %>%
        officer::body_add_par(value = varplot_name, style = "graphic title") %>%
        officer::body_add_break() %>%
        officer::body_add_par("Statistical Tables", style = "heading 2") %>%
        flextable::body_add_flextable(value = correl_tab, align = "left", topcaption = TRUE, split = FALSE) %>%
        officer::body_add_break() %>%
        flextable::body_add_flextable(value = contrib_tab, align = "left", topcaption = TRUE, split = FALSE) %>%
        officer::body_add_par("The contribution describes how much (in %) of the PC is composed of that variable; a more precise definition is that it is the variable's Eigenvecector^2 when the sum of Eigenvecectos^2 (over all variables) is equal to 1 (100%) for each PC (this condition is implicit in PCA). The Eigenvector represents both the magnitude and direction of change of the principal component for each unit increase of the variable. This variable is in the standardized scale (z-score normalized) if scale and center arguments are set to TRUE.", style = "Normal") %>%
        officer::body_add_break()
    }

    # Create long database for boxplots
    if(missing_method == "na_omit") {
      if(treatment_conds_i %in% c("none")){
        base_factor = interaction(multivar_db_ori[, factors_cols], sep = " ")
        second_factor = "none"
      }
      if(treatment_conds_i %in% c("pooled2", "facet2")) {
        base_factor = multivar_db_ori[, factors_cols[1]]
        second_factor = multivar_db_ori[, factors_cols[2]]
      }
      if(treatment_conds_i %in% c("pooled1", "facet1")) {
        base_factor = multivar_db_ori[, factors_cols[2]]
        second_factor = multivar_db_ori[, factors_cols[1]]
      }
    } else {
      base_factor = plot_db$base_factor
      second_factor = if(treatment_conds_i == "none"){"none"} else {plot_db$second_factor}
    }

    # Create long database from plot_db
    plot_db_long = data.frame(cbind(base_factor = base_factor,
                                    second_factor = second_factor,
                                    matrix_values_ori) %>%
                                tidyr::pivot_longer(cols = 3:(2 + length(values_cols)),
                                                    names_to = "variable", values_to = "values"))
    plot_db_long$variable = gsub("\\.", " ", plot_db_long$variable)

    # Create boxplots with variables facet
    box_num = length(unique(plot_db_long$base_factor)) * facet_col
    point_size_algo = 2.5 - (box_num - 2)/20
    box_height = 1.75 + 1.1 * facet_row + ifelse(boxplot_legend_pos %in% c("top", "bottom"), 1.2, 0) +
      ifelse(boxplot_legend_pos == "none", 0.8, 0)
    box_height = box_height * box_ratio

    # Modifying base boxplot aesthethics
    boxplot$data = plot_db_long
    boxplot$guides = guides(colour = guide_legend(base_factor_name, nrow = 1),
                            fill = guide_legend(base_factor_name, nrow = 1),
                            shape = guide_legend(base_factor_name, nrow = 1))
    if(boxplot_legend_pos %in% c("right", "left")){
      boxplot$guides = guides(colour = guide_legend(base_factor_name, ncol = 1),
                              fill = guide_legend(base_factor_name, ncol = 1),
                              shape = guide_legend(base_factor_name, ncol = 1))
    }

    if(boxplot_points == TRUE) {
      boxplot$layers[[3]] = geom_jitter(width = jit_width, height = 0, shape = point_shape, size = point_size_algo, na.rm = TRUE,
                                        alpha = point_alpha)
    }
    boxplot = boxplot +
      facet_wrap(~ variable, ncol = facet_col, nrow = facet_row, scales = "free_y") +
      ylab("Value") + safuncs::theme_Publication() +
      theme(legend.position = boxplot_legend_pos,
            legend.margin = margin(0, 0, 0, 0),
            legend.spacing.x = unit(0, "mm"),
            legend.spacing.y = unit(0, "mm"),
            plot.margin = unit(c(0.07, 0.07, 0.07, 0.07), "in"),
            strip.text = element_text(size = 10, margin = margin(0.155, 0.1, 0.155, 0.1, unit = "cm")),
            strip.background = element_rect(fill = "grey", color = NA))
    if(boxplot_x_lab == TRUE) {boxplot <- boxplot + xlab(base_factor_name)}
    if(boxplot_filled == TRUE) {
      boxplot$mapping = aes(y = values, x = base_factor, fill = base_factor)
    } else {
      boxplot$mapping = aes(y = values, x = base_factor, colour = base_factor)
    }

    # Below is to save plots with variables facet for none and pooling conditions
    if(treatment_conds_i %in% c("none", "pooled1", "pooled2")) {
      # Put in statistical letters
      boxplot$layers[[layer_count]] = NULL
      
      if(treatment_conds_i == "none"){
        
        cld_db0_plotb = cbind(cld_db0, layer_data(boxplot))
        cld_db0_plotb$variable = gsub("\\.", " ", cld_db0_plotb$Variable)
        cld_db0_plotb$Statistical_Classes = gsub(" ", "", cld_db0_plotb$Statistical_Classes, fixed = TRUE)
        
        boxplot$layers[[layer_count]] = ggrepel::geom_text_repel(data = cld_db0_plotb, segment.color = NA, show.legend = FALSE,
                                        size = base_text_size + 2 * (point_size_algo / 3),  
                                        aes(x = x, y = ymax, label = Statistical_Classes, fill = NULL, colour = NULL),
                                        nudge_y = diff(layer_scales(boxplot)$y$range$range) * nudge_y_ratio)
      }
      
      if(treatment_conds_i %in% c("pooled1", "pooled2")){
        cld_db_plot = cld_db[cld_db$Factor == base_factor_name, ]
        boxplot_db = layer_data(boxplot)
        cld_db_plotb = cbind(cld_db_plot, boxplot_db)
        cld_db_plotb$variable = gsub("\\.", " ", cld_db_plotb$Variable)
        cld_db_plotb$Statistical_Classes = gsub(" ", "", cld_db_plotb$Statistical_Classes, fixed = TRUE)
        
        boxplot$layers[[layer_count]] = ggrepel::geom_text_repel(data = cld_db_plotb, segment.color = NA, show.legend = FALSE,
                                        size = base_text_size + 2 * (point_size_algo / 3),  
                                        aes(x = x, y = ymax, label = Statistical_Classes, fill = NULL, colour = NULL),
                                        nudge_y = diff(layer_scales(boxplot)$y$range$range) * nudge_y_ratio)
      }
      
      boxplot_name = ifelse(treatment_conds_i == "none", "Boxplot of Values Facet-Variables",
                            paste("Boxplot of Values Facet-Variables Pooled-", second_factor_name, sep = ""))
      if(boxplot_letters == FALSE) {boxplot$layers[[layer_count]] = NULL}
      boxplot_list[[treatment_conds_i]][["facetvariables"]] = boxplot

      if(plot_out_pptx == TRUE) {
        eoffice::topptx(figure = boxplot, filename = pptx_name,
                        width = box_width, height = box_height, append = TRUE)
      }

      ggsave(plot = suppressWarnings(boxplot), filename = paste(sep = "", boxplot_name, ".png"), path = img_path,
             dpi = 600, width = box_width, height = box_height)
      results_doc_boxplot = results_doc_boxplot %>%
        officer::body_add_img(sr = file.path(img_path, paste(sep = "", boxplot_name, ".png")),
                              width = box_width, height = box_height) %>%
        officer::body_add_par(value = boxplot_name, style = "graphic title") %>%
        officer::body_add_par("") %>%
        officer::body_add_par("")
    }

    # Below is to create plots with variable faceted plots with groups
    if(treatment_conds_i %in% c("pooled1", "pooled2")){
      point_size_algo = 2.9 - (box_num * length(unique(plot_db_long$second_factor)) - 2)/15
      if(boxplot_points == TRUE){
        boxplot$layers[[3]] = geom_point(position = position_jitterdodge(jitter.width = jit_width, jitter.height = 0,
                                                                         dodge.width = dodge_width),
                                         shape = point_shape, size = point_size_algo, na.rm = TRUE, alpha = point_alpha)
      }
      if(boxplot_filled == TRUE){
        boxplot$mapping = aes(y = values, x = base_factor, fill = second_factor)
      } else {
        boxplot$mapping = aes(y = values, x = base_factor, colour = second_factor)
      }
      boxplot$guides = guides(colour = guide_legend(second_factor_name, nrow = 1),
                              fill = guide_legend(second_factor_name, nrow = 1),
                              shape = guide_legend(second_factor_name, nrow = 1))

      if(boxplot_legend_pos %in% c("right", "left")){
        boxplot$guides = guides(colour = guide_legend(second_factor_name, ncol = 1),
                                fill = guide_legend(second_factor_name, ncol = 1),
                                shape = guide_legend(second_factor_name, ncol = 1))
      }
      
      # Put in statistical letters
      if(treatment_conds_i %in% c("pooled1", "pooled2")){
        cld_db2_plot = cld_db2[cld_db2$Factor == second_factor_name,]
        boxplot_db = layer_data(boxplot)
        cld_db2_plotb = cbind(cld_db2_plot, boxplot_db)
        cld_db2_plotb$variable = gsub("\\.", " ", cld_db2_plotb$Variable)
        cld_db2_plotb$Statistical_Classes = gsub(" ", "", cld_db2_plotb$Statistical_Classes, fixed = TRUE)
        
        boxplot$layers[[layer_count]] = ggrepel::geom_text_repel(data = cld_db2_plotb, segment.color = NA, show.legend = FALSE,
                                        size = base_text_size + 2 * (point_size_algo / 3),  
                                        aes(x = x, y = ymax, label = Statistical_Classes, fill = NULL, colour = NULL),
                                        nudge_y = diff(layer_scales(boxplot)$y$range$range) * nudge_y_ratio)
      }

      save_name = ifelse(treatment_conds_i == "pooled1", "facetvariables1", "facetvariables2")
      boxplot_name = paste(sep = "", "Boxplot of Values Facet-Variables Grouped-", second_factor_name)
      if(boxplot_letters == FALSE) {boxplot$layers[[layer_count]] = NULL}
      boxplot_list[[treatment_conds_i]][[save_name]] = boxplot

      if(plot_out_pptx == TRUE) {
        eoffice::topptx(figure = boxplot, filename = pptx_name,
                        width = box_width, height = box_height, append = TRUE)
      }

      ggsave(plot = suppressWarnings(boxplot), filename = paste(sep = "", boxplot_name, ".png"), path = img_path,
             dpi = 600, width = box_width, height = box_height)

      results_doc_boxplot = results_doc_boxplot %>%
        officer::body_add_img(sr = file.path(img_path, paste(sep = "", boxplot_name, ".png")),
                              width = box_width, height = box_height) %>%
        officer::body_add_par(value = boxplot_name, style = "graphic title") %>%
        officer::body_add_par("") %>%
        officer::body_add_par("")
    }

    if(treatment_conds_i %in% c("facet1", "facet2")) {
      results_doc_boxplot = results_doc_boxplot %>%
        officer::body_add_par(paste("NOTE: Plots with facets by",
                                    second_factor_name, "can only be created by removing facets by variables. To achieve this, use 'boxplot_var_sep' == TRUE.")) %>%
        officer::body_add_par("")
    }

    # Create boxplots without variables facet, for each separate variable.
    if(boxplot_var_sep == TRUE) {
      box_num = length(unique(plot_db_long$base_factor)) * ifelse(treatment_conds_i %in% c("facet1", "facet2"), facet_col, 1)
      box_row = ifelse(treatment_conds_i %in% c("facet1", "facet2"), facet_row, 1)
      point_size_algo = 2.9 - (box_num - 2)/20

      box_height2 = 2.05 + (1.1 * box_row) + ifelse(box_num <= 6, 0.4, 0) +
        ifelse(boxplot_legend_pos %in% c("bottom", "top"), 0.8, 0) + ifelse(boxplot_legend_pos == "none", 0.8, 0)
      box_height2 = box_height2 * box_ratio

      for(values_cols_i in values_cols) {
        varname = gsub("\\.", " ", colnames(multivar_db)[values_cols_i])
        boxplot$layers[[layer_count]] = NULL
        
        # Filter for a variable
        plot_db_long_filtered = plot_db_long[plot_db_long$variable == varname, ]

        # Change boxplot data, point size, facet and names
        boxplot = boxplot +
          ylab(varname) +
          theme(strip.text = element_blank(),
                strip.background = element_blank())
                #plot.margin = unit(c(0.0 + (0.04 * box_num), 0.05, 0.05 + (0.01 * box_num), 0.05), "in"))
        boxplot$data = plot_db_long_filtered
        if(boxplot_points == TRUE) {
          boxplot$layers[[3]] = geom_jitter(width = jit_width, height = 0, shape = point_shape, size = point_size_algo, na.rm = TRUE,
                                            alpha = point_alpha)
        }

        if(treatment_conds_i %in% c("facet2", "facet1")) {
          boxplot$layers[[layer_count]] = NULL
          boxplot$facet = facet_wrap(~ second_factor, ncol = facet_col, nrow = facet_row)
          boxplot = boxplot + safuncs::theme_Publication() +
            theme(legend.position = boxplot_legend_pos,
                  legend.margin = margin(0, 0, 0, 0),
                  legend.spacing.x = unit(0, "mm"),
                  legend.spacing.y = unit(0, "mm"),
                  plot.margin = unit(c(0.07, 0.07, 0.07, 0.07), "in"),
                  strip.text = element_text(size = 10, margin = margin(0.155, 0.1, 0.155, 0.1, unit = "cm")),
                  strip.background = element_rect(fill = "grey", color = NA))
          boxplot_name = paste("Boxplot of ", varname, " Facet-", second_factor_name, sep = "")
          
          cld_db2_plot = cld_db2[cld_db2$Factor == base_factor_name & cld_db2$Variable == colnames(multivar_db)[values_cols_i],]
          boxplot_db = layer_data(boxplot)
          cld_db2_plotb = cbind(cld_db2_plot, boxplot_db)
          cld_db2_plotb$variable = gsub("\\.", " ", cld_db2_plotb$Variable)
          cld_db2_plotb$second_factor = cld_db2_plotb$Condition
          cld_db2_plotb$Statistical_Classes = gsub(" ", "", cld_db2_plotb$Statistical_Classes, fixed = TRUE)
          
          # Add statistical letters
          boxplot$layers[[layer_count]] = ggrepel::geom_text_repel(data = cld_db2_plotb, segment.color = NA,
                                        size = base_text_size + 2.6 * (point_size_algo2 / 3), show.legend = FALSE,
                                        aes(x = x, y = ymax, label = Statistical_Classes, fill = NULL, colour = NULL),
                                        nudge_y = diff(layer_scales(boxplot)$y$range$range) * nudge_y_ratio)
          
        }
        if(treatment_conds_i == "none") {
          boxplot_name = paste("Boxplot of ", varname, sep = "")
          boxplot$layers[[layer_count]] = NULL
          
          boxplot$layers[[layer_count]] = ggrepel::geom_text_repel(data = cld_db0_plotb[cld_db0_plotb$variable == varname, ], 
                                          size = base_text_size + 2.6 * (point_size_algo / 3), segment.color = NA,
                                          aes(x = x, y = ymax, label = Statistical_Classes, fill = NULL, colour = NULL),
                                          nudge_y = diff(layer_scales(boxplot)$y$range$range) * nudge_y_ratio,
                                          show.legend = FALSE)
        }
        if(treatment_conds_i %in% c("pooled2", "pooled1")) {
          boxplot_name = paste("Boxplot of ", varname, " Pooled-", second_factor_name, sep = "")
          boxplot_name2 = paste("Boxplot of ", varname, " Grouped-", second_factor_name, sep = "")
          boxplot2 = boxplot
          if(boxplot_filled == TRUE){
            boxplot$mapping = aes(x = base_factor, fill = base_factor, y = values)
            boxplot2$mapping = aes(x = base_factor, fill = second_factor, y = values)
          } else {
            boxplot$mapping = aes(x = base_factor, colour = base_factor, y = values)
            boxplot2$mapping = aes(x = base_factor, colour = second_factor, y = values)
          }
          point_size_algo2 = 3 - (box_num * length(unique(plot_db_long$second_factor)) - 2)/20
          if(boxplot_points == TRUE) {
            boxplot2$layers[[3]] = geom_point(position = position_jitterdodge(jitter.width = jit_width, jitter.height = 0,
                                                                              dodge.width = dodge_width),
                                              shape = point_shape, size = point_size_algo2,
                                              na.rm = TRUE, alpha = point_alpha)
          }
          boxplot$guides = guides(colour = guide_legend(base_factor_name, nrow = 1),
                                  fill = guide_legend(base_factor_name, nrow = 1),
                                  shape = guide_legend(base_factor_name, nrow = 1))
          if(boxplot_legend_pos %in% c("right", "left")){
            boxplot$guides = guides(colour = guide_legend(base_factor_name, ncol = 1),
                                    fill = guide_legend(base_factor_name, ncol = 1),
                                    shape = guide_legend(base_factor_name, ncol = 1))
          }
          
          #Put in statistical letters
          boxplot$layers[[layer_count]] = ggrepel::geom_text_repel(data = cld_db_plotb[cld_db_plotb$variable == varname, ], 
                                        size = base_text_size + 3 * (point_size_algo / 3), segment.color = NA, show.legend = FALSE,
                                        aes(x = x, y = ymax, label = Statistical_Classes, fill = NULL, colour = NULL),
                                        nudge_y = diff(layer_scales(boxplot)$y$range$range) * nudge_y_ratio)
          
          boxplot2$layers[[layer_count]] = ggrepel::geom_text_repel(data = cld_db2_plotb[cld_db2_plotb$variable == varname, ],
                                        size = base_text_size + 3 * (point_size_algo2 / 3), segment.color = NA, show.legend = FALSE,
                                        aes(x = x, y = ymax, label = Statistical_Classes, fill = NULL, colour = NULL),
                                        nudge_y = diff(layer_scales(boxplot2)$y$range$range) * nudge_y_ratio)
          
          if(boxplot_letters == FALSE) {boxplot2$layers[[layer_count]] <- NULL}
          
          boxplot_list[[gsub("pooled", "grouped", treatment_conds_i)]][[varname]] = boxplot2
          boxplot_name_vec = c(boxplot_name_vec, boxplot_name2)
          box_height2_vec = c(box_height2_vec, box_height2)

          ggsave(plot = suppressWarnings(boxplot2), filename = paste(boxplot_name2, ".png", sep = ""),
                 dpi = 600, width = box_width, height = box_height2, path = img_path)

          if(plot_out_pptx == TRUE) {
            eoffice::topptx(figure = boxplot2, filename = pptx_name,
                            width = box_width, height = box_height2, append = TRUE)
          }
        }

        boxplot_name_vec = c(boxplot_name_vec, boxplot_name)
        box_height2_vec = c(box_height2_vec, box_height2)

        # Save all non grouped boxplots
        if(boxplot_letters == FALSE) {boxplot$layers[[layer_count]] <- NULL}
        boxplot_list[[treatment_conds_i]][[varname]] = boxplot

        if(plot_out_pptx == TRUE) {
          eoffice::topptx(figure = boxplot, filename = pptx_name,
                          width = box_width, height = box_height2, append = TRUE)
        }
        ggsave(plot = suppressWarnings(boxplot), filename = paste(boxplot_name, ".png", sep = ""),
               dpi = 600, width = box_width, height = box_height2, path = img_path)
      }

      # Add them to results_doc
      if(treatment_conds_i == last(treatment_conds)){
        i = 0
        pooled_indices = grep("Pooled", boxplot_name_vec)
        grouped_indices = grep("Grouped", boxplot_name_vec)
        facet_indices = grep("Facet", boxplot_name_vec)
        other_indices = setdiff(1:length(boxplot_name_vec), c(pooled_indices, grouped_indices, facet_indices))
        boxplot_name_vec = boxplot_name_vec[c(other_indices, pooled_indices, grouped_indices, facet_indices)]
        for(boxplot_name_i in boxplot_name_vec) {
          i = i + 1
          if(i == 1) {
            results_doc_boxplot = results_doc_boxplot %>%
              officer::body_add_par(value = "Variables in Separate Plots", style = "heading 2")
          }

          results_doc_boxplot = results_doc_boxplot %>%
            officer::body_add_img(sr = file.path(img_path, paste(boxplot_name_i, ".png", sep = "")),
                                  width = box_width, height = box_height2_vec[i]) %>%
            officer::body_add_par(value = boxplot_name_i, style = "graphic title") %>%
            officer::body_add_par("") %>%
            officer::body_add_par("")
        }
      }
    }

    # Create LDA, MANOVA and potentially ANOVA tables
    if(last(treatment_conds) == treatment_conds_i) {
      results_doc_boxplot = results_doc_boxplot %>% officer::body_add_break()

      # Create LDA table results
      lda_db = cbind(multivar_db[, factors_cols, drop = FALSE],
                     scale(matrix_values[,!colnames(matrix_values) %in% c("PC1", "PC2")],
                           scale = scale, center = center))
      values_vec = paste(collapse = " + ", colnames(lda_db[, (1 + length(factors_cols)):ncol(lda_db)]))

      for(lda_factor in colnames(multivar_db[, factors_cols, drop = FALSE])){
        
        # Fit LDA mod
        lda_mod = MASS::lda(formula = as.formula(paste(lda_factor, "~", values_vec)),
                            data = lda_db)

        # Store LDA results in a table and list
        lda_contrib = (scale(lda_mod$scaling, F, sqrt(colSums(lda_mod$scaling^2))))^2
        lda_contrib_db = data.frame(Variable = gsub("\\.", " ", rownames(lda_contrib)),
                                    Contrib.LD1 = 100 * lda_contrib[, 1],
                                    Coeff.LD1 = lda_mod$scaling[, 1])
        if(ncol(lda_contrib) > 1) {
          lda_contrib_db$Contrib.LD2 = 100 * lda_contrib[, 2]
          lda_contrib_db$Coeff.LD2 = lda_mod$scaling[, 2]
        }

        tc = tc + 1
        lda_contrib_db = lda_contrib_db %>% dplyr::arrange(dplyr::desc(Contrib.LD1))
        lda_contrib_tab = flextable::flextable(lda_contrib_db) %>%
          flextable::set_caption(caption = paste("Table ", tc, ". Contribution of variables to linear discriminants of ",
                                                 lda_factor, sep = "")) %>%
          flextable::set_table_properties(layout = "autofit", width = 1) %>%
          flextable::bold(bold = TRUE, part = "header")

        lda_exp = round(100 * (lda_mod$svd^2 / sum(lda_mod$svd^2)), 1)

        # Add results to officer
        results_doc = results_doc %>%
          flextable::body_add_flextable(value = lda_contrib_tab, align = "left", topcaption = TRUE, split = FALSE) %>%
          officer::body_add_par(value = paste(sep = "", "LD1 and LD2 explain ", lda_exp[1], "% and ", lda_exp[2],
                                              "% of the separation between ", lda_factor, ", respectively."), style = "Normal") %>%
          officer::body_add_par("")
      }

      results_doc = results_doc %>%
        officer::body_add_par("Tabulated values are based on Linear Discriminant Analysis (LDA). The contribution describes the percentage of the linear discriminant composed of that variable; a more exact definition is that it is the variable's coefficient of linear discriminant^2 when the sum of coefficients^2 (across variables) is normalized to 100%. The coefficient of linear discriminant describes the magnitude and direction of change in the linear discriminant score (towards a particular factor level) per unit increase of the variable. Apart from the coefficients relative signs and magnitude, they may be difficult to interpret without an associated LDA plot.", style = "Normal")

      # Get MANOVA results
      manova_db = cbind(multivar_db[, factors_cols, drop = FALSE],
                        matrix_values[,!colnames(matrix_values) %in% c("PC1", "PC2")])
      values_vec2 = paste("cbind(",
                          paste(collapse = ",", colnames(manova_db[, (1 + length(factors_cols)):ncol(manova_db)])),
                          ")", sep = "")

      options(contrasts = c("contr.sum", "contr.poly"))
      #permanova = suppressWarnings(RVAideMemoire::adonis.II(formula = as.formula(paste(values_vec, "~", factors_vec)),
                                                            #data = manova_db, method = "euclidean"))
      manova_mod = manova(formula = as.formula(paste(values_vec2, "~", factors_vec)),
                          data = manova_db)
      manova = car::Anova(type = 3, manova_mod)
      options(contrasts = c("contr.treatment", "contr.poly"))
      manova_p = suppressWarnings(as.numeric(na.omit(as.numeric(sub(".*\\s*(\\d+\\.[0-9e-]+)\\s*[*.]*",
                                                                    "\\1", capture.output(manova))))))

      # Create MANOVA table
      manova_db = data.frame(Factor = manova$terms[!manova$terms == "(Intercept)"],
                             #PERMANOVA = as.numeric(na.omit(permanova$`Pr(>F)`)),
                             P_value = sapply(manova_p[!manova$terms == "(Intercept)"], knife))
      #manova_db$PERMANOVA = ifelse(manova_db$PERMANOVA < 0.001, formatC(manova_db$PERMANOVA, format = "e", digits = 4), manova_db$PERMANOVA)
      #manova_db = manova_db[, -2] #exclude PERMANOVA results for now to prevent confusion. May add some time in the future.
      colnames(manova_db) = gsub("_", " ", colnames(manova_db))

      tc = tc + 1
      manova_tab = flextable::flextable(manova_db) %>%
        flextable::set_caption(caption = paste("Table ", tc, ". MANOVA Results", sep = "")) %>%
        flextable::set_table_properties(layout = "autofit", width = 1) %>%
        flextable::bold(bold = TRUE, part = "header")

      results_doc = results_doc %>%
        officer::body_add_break() %>%
        flextable::body_add_flextable(value = manova_tab, align = "left", topcaption = TRUE, split = FALSE) %>%
        officer::body_add_par("")
      
      # MANOVA pairwise comparisons
      manova_pairs_con2_db = data.frame()
      for(factor_conds_i in factor_conds){
        nest_fac = NULL
        if(length(factors_cols) == 2) {nest_fac <- factor_conds[!factor_conds == factor_conds_i]}
        manova_pairs = biotools::mvpaircomp(manova_mod, factor_conds_i, adjust = "BH", 
                                            nesting.factor = nest_fac)
        
        manova_p_col_vec = seq(5, ncol(data.frame(manova_pairs$st)), 5) 
        if(length(factors_cols) == 1) {
          manova_pairs_con2_db = rbind(manova_pairs_con2_db,
                                       data.frame(Contrast = rownames(data.frame(manova_pairs$st)),
                                                  P_value = sapply(c(data.frame(manova_pairs$st)[, manova_p_col_vec]),
                                                                   knife)))
          merge_g = c("Contrast")
        } else {
        manova_pairs_con2_db = rbind(manova_pairs_con2_db,
                                     data.frame(Condition = rep(levels(
                                                  factor(multivar_db[,factor_conds[!factor_conds == factor_conds_i]])),
                                                  each = nrow(manova_pairs$st)),
                                                Contrast = rownames(data.frame(manova_pairs$st)),
                                                P_value = sapply(stack(c(data.frame(manova_pairs$st)[, manova_p_col_vec]))$values,
                                                                 knife))) 
        merge_g = c("Condition", "Contrast")
        }
      }
      colnames(manova_pairs_con2_db) = gsub("_", " ", colnames(manova_pairs_con2_db))
      
      if(length(factors_cols) == 1){
        tite2 = ". MANOVA Pairwise Comparison Results"
        tite2b = "P-values were generated from pairwise comparisons of levels of a factor. Comparisons were conducted using the function mvpaircomp() with the Benjamini Hochberg correction to control for a False Discovery Rate of 5%."
      } else {
        tite2 = ". MANOVA 'Conditional' Pairwise Comparison Results"
        tite2b = "P-values were generated from pairwise comparisons of levels of a factor, while holding a level from another factor constant. Comparisons were conducted using the function mvpaircomp() with the Benjamini Hochberg correction to control for a False Discovery Rate of 5%.. mvpaircomp() used the two-factor MANOVA model with interactions."
      }
      
      tc = tc + 1
      manova_con2_tab = flextable::flextable(manova_pairs_con2_db) %>%
      flextable::set_caption(caption = paste("Table ", tc, tite2, sep = "")) %>%
      flextable::set_table_properties(layout = "autofit", width = 1) %>%
      flextable::colformat_double(digits = 5) %>%
      flextable::merge_v(j = merge_g) %>%
      flextable::valign(j = merge_g, valign = "top") %>%
      flextable::theme_vanilla()
      
      results_doc = results_doc %>%
      flextable::body_add_flextable(value = manova_con2_tab, align = "left", topcaption = TRUE, split = FALSE) %>%
      officer::body_add_par(paste(tite2b)) %>%
      officer::body_add_par("") %>%
      officer::body_add_break()
  
        #p_bh = p.adjust(p_no_adj, method = "BH")

        # Create ANOVA p-values table
        anova_fac = rownames(data.frame(Anova_res))[-c(1, length(rownames(data.frame(Anova_res))))]
        p_db = data.frame(Variable = rep(varnames_vec, each = length(anova_fac)),
                          Factor = rep(anova_fac, times = length(varnames_vec)),
                          P_value = sapply(p_no_adj, knife))
        p_db$Variable = gsub("\\.", " ", p_db$Variable)

        tc = tc + 1
        colnames(p_db) = gsub("_", " ", colnames(p_db))
        p_tab = flextable::flextable(p_db) %>%
          flextable::set_caption(caption = paste("Table ", tc, ". ANOVA Results", sep = "")) %>%
          flextable::set_table_properties(layout = "autofit", width = 1) %>%
          flextable::merge_v(j = c("Variable")) %>%
          flextable::valign(j = c("Variable"), valign = "top") %>%
          flextable::theme_vanilla() %>%
          flextable::bold(bold = TRUE, part = "header")

        # Create cld table (simple)
        if(length(factors_cols) == 1) {
          cld_db = cld_db0[order(cld_db0$Variable, cld_db0$Levels),]
          contrast_db = contrast_db0[order(contrast_db0$Variable, contrast_db0$Contrast),]
          col_ord = c("Variable")
          titex = ". Statistical Classes from 'Complete' Pairwise Comparisons"
        } else {
          cld_db = cld_db[order(cld_db$Factor),]
          contrast_db = contrast_db[order(contrast_db$Factor),]
          col_ord = c("Factor", "Variable")
          titex = ". Statistical Classes from 'Pooled' Pairwise Comparisons"
        } 
        cld_db$Variable = gsub("\\.", " ", cld_db$Variable)
        colnames(cld_db) = gsub("_", " ", colnames(cld_db))
        
        tc = tc + 1
        cld_tab = flextable::flextable(cld_db) %>%
          flextable::set_caption(caption = paste("Table ", tc, titex, sep = "")) %>%
          flextable::set_table_properties(layout = "autofit", width = 1) %>%
          flextable::merge_v(j = col_ord) %>%
          flextable::valign(j = col_ord, valign = "top") %>%
          flextable::theme_vanilla()

        # Create contrast table (simple)
        contrast_db$Variable = gsub("\\.", " ", contrast_db$Variable)
        
        tc = tc + 1
        colnames(contrast_db) = gsub("_", " ", colnames(contrast_db))
        contrast_tab = flextable::flextable(contrast_db) %>%
          flextable::set_caption(caption = paste("Table ", tc, titex, sep = "")) %>%
          flextable::colformat_double(digits = 5) %>%
          flextable::set_table_properties(layout = "autofit", width = 1) %>%
          flextable::merge_v(j = col_ord) %>%
          flextable::valign(j = col_ord, valign = "top") %>%
          flextable::theme_vanilla()

        if(length(factors_cols) == 2){

          # Create cld table (conditional)
          cld_db2 = cld_db2[order(cld_db2$Factor),]
          cld_db2$Variable = gsub("\\.", " ", cld_db2$Variable)
          
          tc = tc + 1
          colnames(cld_db2) = gsub("_", " ", colnames(cld_db2))
          cld_db2 = cld_db2[, -1]
          cld_tab2 = flextable::flextable(cld_db2) %>%
            flextable::set_caption(caption = paste("Table ", tc,
                                                   ". Statistical Classes from 'Conditional' Comparisons", sep = "")) %>%
            flextable::set_table_properties(layout = "autofit", width = 1) %>%
            flextable::merge_v(j = c("Variable", "Condition")) %>%
            flextable::valign(j = c("Variable", "Condition"), valign = "top") %>%
            flextable::theme_vanilla()

          # Create contrast table (conditional)
          contrast_db2 = contrast_db2[order(contrast_db2$Factor),]
          contrast_db2$Variable = gsub("\\.", " ", contrast_db2$Variable)

          tc = tc + 1
          colnames(contrast_db2) = gsub("_", " ", colnames(contrast_db2))
          contrast_db2 = contrast_db2[, -1]
          contrast_tab2 = flextable::flextable(contrast_db2) %>%
            flextable::set_caption(caption = paste("Table ", tc,
                                                   ". 'Conditional' Pairwise Comparison Results", sep = "")) %>%
            flextable::colformat_double(digits = 5) %>%
            flextable::set_table_properties(layout = "autofit", width = 1) %>%
            flextable::merge_v(j = c("Variable", "Condition", "Contrast")) %>%
            flextable::valign(j = c("Variable", "Condition", "Contrast"), valign = "top") %>%
            flextable::theme_vanilla()
          
          # Create cld table (complete)
          cld_db0$Variable = gsub("\\.", " ", cld_db0$Variable)
          
          tc = tc + 1
          colnames(cld_db0) = gsub("_", " ", colnames(cld_db0))
          cld_tab0 = flextable::flextable(cld_db0) %>%
            flextable::set_caption(caption = paste("Table ", tc,
                                                   ". Statistical Classes from 'Complete' Comparisons", sep = "")) %>%
            flextable::set_table_properties(layout = "autofit", width = 1) %>%
            flextable::merge_v(j = c("Variable", "Levels")) %>%
            flextable::valign(j = c("Variable", "Levels"), valign = "top") %>%
            flextable::theme_vanilla()

          # Create contrast table (complete)
          contrast_db0$Variable = gsub("\\.", " ", contrast_db0$Variable)

          tc = tc + 1
          colnames(contrast_db0) = gsub("_", " ", colnames(contrast_db0))
          contrast_tab0 = flextable::flextable(contrast_db0) %>%
            flextable::set_caption(caption = paste("Table ", tc,
                                                   ". 'Complete' Pairwise Comparison Results", sep = "")) %>%
            flextable::colformat_double(digits = 5) %>%
            flextable::set_table_properties(layout = "autofit", width = 1) %>%
            flextable::merge_v(j = c("Variable", "Contrast")) %>%
            flextable::valign(j = c("Variable", "Contrast"), valign = "top") %>%
            flextable::theme_vanilla()
        }

        # Add results to word output
        results_doc_boxplot = results_doc_boxplot %>%
          officer::body_add_par("Statistical Tables", style = "heading 2") %>%
          flextable::body_add_flextable(value = p_tab, align = "left", topcaption = TRUE, split = FALSE) %>%
          officer::body_add_par(ifelse(length(factors_cols) == 2, "Type 3 SS ANOVAs were conducted.", "")) %>%
          officer::body_add_par("") %>%
          flextable::body_add_flextable(value = cld_tab, align = "left", topcaption = TRUE, split = FALSE) %>%
          officer::body_add_par(paste("Different letters denote significantly different levels of a factor. All levels within a factor were compared pairwise using the function emmeans() with the Benjamini Hocherbg correction to control for a False Discovery Rate of 5%.", ifelse(length(factors_cols) == 2, "emmeans() were based on two-factor models (with interactions) fitted separately by variable.", ""))) %>%
          officer::body_add_par("") %>%
          flextable::body_add_flextable(value = contrast_tab, align = "left", topcaption = TRUE, split = FALSE) %>%
          officer::body_add_par(paste("P-values were generated from pairwise comparisons of levels of a factor. Comparisons conducted using the function emmeans() with the Benjamini Hochberg correction to control for a False Discovery Rate of 5%.", ifelse(length(factors_cols) == 2, "emmeans() were based on two-factor models (with interactions) fitted separately by variable.", ""))) %>%
          officer::body_add_par("")

        if(length(factors_cols) == 2) {
          results_doc_boxplot = results_doc_boxplot %>%
            flextable::body_add_flextable(value = cld_tab2, align = "left", topcaption = TRUE, split = FALSE) %>%
            officer::body_add_par("Different letters denote significantly different levels of a factor. Levels were compared pairwise within a factor while holding a level from another factor constant. Comparisons conducted using the function emmenas() with the Benjamini Hochberg correction to control for a False Discovery Rate of 5%. emmeans() were based on two-factor models (with interactions) fitted separately by variable.") %>%
            officer::body_add_par("") %>%
            flextable::body_add_flextable(value = contrast_tab2, align = "left", topcaption = TRUE, split = FALSE) %>%
            officer::body_add_par("P-values were generated from pairwise comparisons of levels of a factor, while holding a level from another factor constant. Comparisons conducted using the function emmeans() with the Benjamini Hochberg correction to control for a False Discovery Rate of 5%. emmeans() were based on two-factor models (with interactions) fitted separately by variable.") %>%
            officer::body_add_par("") %>%
            flextable::body_add_flextable(value = cld_tab0, align = "left", topcaption = TRUE, split = FALSE) %>%
            officer::body_add_par("Different letters denote significantly different levels. All level combinations were compared pairwise. Comparisons conducted using the function emmenas() with the Benjamini Hochberg correction to control for a False Discovery Rate of 5%. emmeans() were based on two-factor models (with interactions) fitted separately by variable.") %>%
            officer::body_add_par("") %>%
            flextable::body_add_flextable(value = contrast_tab0, align = "left", topcaption = TRUE, split = FALSE) %>%
            officer::body_add_par("P-values were generated from pairwise comparisons of all combination of levels. Comparisons conducted using the function emmeans() with the Benjamini Hochberg correction to control for a False Discovery Rate of 5%. emmeans() were based on two-factor models (with interactions) fitted separately by variable.")
        }
      }
    }

  # Save word document
  print(results_doc_boxplot, target = tempf)
  print(officer::body_add_docx(results_doc, src = tempf),
        target = paste(sep = "", "MultiVar Report ", format(Sys.Date(), "%d%b%Y"), ".docx"))

  # Delete temporary files
  file.remove(tempf)
  if(plot_out_png == FALSE) {unlink(img_path)}

  # Print plot output in R
  if(plot_out_R == TRUE) {
    return(list(pca = pca_list,
                correl = varplot,
                box = boxplot_list))
  }
  boxplot_list
```

