---
title: "Testing Grounds"
output: 
  rmdformats::readthedown:
    code_download: true
date: '`r format(Sys.time(), "%d %B, %Y")`'
---

# Heading 1

```{r}
remotes::install_github("sean4andrew/safuncs2")
use_package() 

```

## Heading 2

Surv_Plots()
```{r}
Surv_Plots = function(surv_db,
                      x_axis_limits,
                      y_axis_limits,
                      x_lab = "Days Post Challenge",
                      lambda1 = NULL,
                      lambda2 = NULL) {
  
  for(split_lev in levels(surv_db$Split)) {
    surv_obj = survival::survfit(Surv(TTE, Status) ~ Treatment, data = surv_db)
    attributes(surv_obj$strata)$names <- levels(as.factor(surv_db$Treatment))
    surv_plot = survminer::ggsurvplot(surv_obj, 
                                      conf.int = FALSE, 
                                      ggtheme = theme(plot.background = element_rect(fill = "white")), 
                                      break.y.by = 0.1, 
                                      break.x.by = 1, 
                                      xlim = x_axis_limits, 
                                      ylim = y_axis_limits, 
                                      xlab = x_lab,
                                      surv.scale = "percent")
    surv_plot$plot + ggplot2::theme(legend.position = "right")
    ggplot2::ggsave(paste("Survival Curve Split_by =", split_lev, ".tiff"), dpi = 300, width = 6, height = 4)
    
    Haz_list = list()
    for(Haz_Trt in levels(as.factor(surv_db$Treatment))) {
      surv_db_trt = surv_db[surv_db$Treatment == Haz_Trt,]
      if(length(levels(as.factor(surv_db_trt$Tank.ID))) > 1) {
        Haz_bs = bshazard::bshazard(nbin = max(surv_db$TTE), 
                                                 data = surv_db_trt, 
                                                 Surv(TTE, Status) ~ Tank.ID, 
                                                 verbose = FALSE)  
      } else {
        Haz_bs = bshazard::bshazard(nbin = max(surv_db$TTE), 
                                                 data = surv_db_trt, 
                                                 Surv(TTE, Status) ~ 1, 
                                                 verbose = FALSE) 
      }
      
      Haz_DB = data.frame(Hazard = Haz_bs$hazard,
                          Time = Haz_bs$time)
      Haz_list[[Haz_Trt]] = data.frame(Hazard = Haz_bs$hazard,
                                       Time = Haz_bs$time)    
    }

      Haz_DB = dplyr::bind_rows(Haz_list)
      ggplot(data = Haz_DB, aes(x = Time, y = Hazard, color = Treatment)) +
        geom_line(linewidth = 1) +
        geom_point() + 
        xlab("Days Post Challenge") +
        scale_x_continuous(breaks = seq(min(x_axis_limits), max(x_axis_limits), 1), limits = x_axis_limits)
      ggplot2::ggsave(paste("Hazard Curve Split_by =", split_lev, ".tiff"), dpi = 300, width = 6, height = 4)
  }
}
```


