---
title: "MultiVar() on Mark Fast Data"
output: html_document
date: "`r Sys.Date()`"
---

1. Installing and loading the package (you only have to install once)
```{r Setup package}
remotes::install_github("sean4andrew/safuncs")
library(safuncs)
```

2. Load dataset
```{r Setup data}
MF_DB = read.csv(file = "Gene expression Mark Fast.csv")[-76,] # remove data point #76 - suspected to be the reference/standard
MF_DB$Date = factor(MF_DB$Date, levels = c("05Jun", "12Jun", "14Aug", "20Aug")) # reorder factor levels

head(MF_DB)
```
2b. Split data. I assume this is what is wanted based on the research questions.
```{r}
MF_DB_Jun = MF_DB[MF_DB$Date %in% c("05Jun", "12Jun"), ]
MF_DB_Aug = MF_DB[MF_DB$Date %in% c("14Aug", "20Aug"), ]
```


3. Running MultiVar()
```{r Run MultiVar()}
MultiVar(multivar_db = MF_DB,
         values_cols = 4:14,
         factors_cols = 1:2,
         factors_facet = c("col1", "col2"),
         missing_method = "na_omit",
         boxplot_filled = TRUE,
         boxplot_x_wrap = 6,
         boxplot_var_sep = TRUE,
         boxplot_points = TRUE,
         plot_out_R = TRUE)
```
